version: '3.7'

services:
    php:
        container_name: app
        build:
            context: ./app
        volumes:
            - ~/git/github/ninaite/:/var/www/ninaite
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_BUCKET: ${AWS_BUCKET}
        depends_on:
            - mysql
        links:
            - mysql
        networks:
            - backend
        ports:
            - 80:80

    mysql:
        image: mysql
        container_name: mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=${TZ}
        volumes:
            - db-store:/var/lib/mysql
            - ~/git/github/ninaite/docker/dev/mysql/conf_d/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - ${DB_PORT}:3306
        networks:
            - backend

volumes:
    db-store:
    db-testing-store:
networks:
    backend:
        driver: bridge
